#!/bin/bash

DOCKER_REGISTRY_ADDRESS=$1
DOCKER_REGISTRY_USR=$2
DOCKER_REGISTRY_PWD=$3
DOCKER_IMAGE_ADDRESS=$4
DOCKER_IMAGE_PREFIX=$5
DOCKER_IMAGE_SUFFIX=$6

DOCKER_IMAGE_TAG="$DOCKER_IMAGE_PREFIX-$DOCKER_IMAGE_SUFFIX"
DOCKER_IMAGE_NAME_TAG="$DOCKER_IMAGE_ADDRESS:$DOCKER_IMAGE_TAG"

echo "Login registry $DOCKER_REGISTRY_ADDRESS"
echo "$DOCKER_REGISTRY_PWD" | docker login "$DOCKER_REGISTRY_ADDRESS" --username "$DOCKER_REGISTRY_USR" --password-stdin
echo "Login registry $DOCKER_IMAGE_PREFIX successfully"

echo "Building image $DOCKER_IMAGE_PREFIX"
docker build -t "$DOCKER_IMAGE_NAME_TAG" .
echo "Building image $DOCKER_IMAGE_PREFIX successfully"

echo "Pushing image $DOCKER_IMAGE_PREFIX"
docker push "$DOCKER_IMAGE_NAME_TAG"
echo "Pushing image $DOCKER_IMAGE_PREFIX successfully"
