#!/bin/bash

DOCKER_REGISTRY_ADDRESS=$1
DOCKER_REGISTRY_USR=$2
DOCKER_REGISTRY_PWD=$3
DOCKER_IMAGE_ADDRESS=$4
DOCKER_IMAGE_PREFIX=$5
DOCKER_IMAGE_SUFFIX=$6

DOCKER_IMAGE_TAG="$DOCKER_IMAGE_PREFIX-$DOCKER_IMAGE_SUFFIX"
DOCKER_IMAGE_NAME_TAG="$DOCKER_IMAGE_ADDRESS:$DOCKER_IMAGE_TAG"

DOCKER_CONTAINER_NAME='preview-cms'

echo "Login registry $DOCKER_REGISTRY_ADDRESS"
echo "$DOCKER_REGISTRY_PWD" | sudo docker login "$DOCKER_REGISTRY_ADDRESS" --username "$DOCKER_REGISTRY_USR" --password-stdin
echo "Login registry $DOCKER_IMAGE_PREFIX successfully"

echo "Running image $DOCKER_IMAGE_PREFIX"
sudo docker pull "$DOCKER_IMAGE_NAME_TAG" && \
  sudo docker stop $DOCKER_CONTAINER_NAME && \
  sudo docker rm $DOCKER_CONTAINER_NAME && \
  sudo docker run -d --name $DOCKER_CONTAINER_NAME -p 1377:1377 "$DOCKER_IMAGE_NAME_TAG"
echo "Running image $DOCKER_IMAGE_PREFIX successfully"
